# 使用官方 nginx 镜像作为基础镜像
FROM nginx

# 将本地的 nginx.conf 复制到容器内的 /etc/nginx/ 目录下
COPY nginx.conf /etc/nginx/nginx.conf

# 将本地的 build 目录下的所有文件复制到容器内的 /usr/share/nginx/html/ 目录下
COPY ../frontend/build/ /usr/share/nginx/html/

# 暴露端口
EXPOSE 80

# 启动 nginx 服务器
CMD ["nginx", "-g", "daemon off;"]
