FROM python:3.9
WORKDIR /app

COPY ../backend/requirements.txt ../backend/api.py ../backend/.flaskenv ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["yarn", "start"]